services:
  fraddriso20022:
    build:
      context: .
      dockerfile: Dockerfile
    image: fraddriso20022:latest
    ports:
      - "8080:8080"
    environment:
      SELECT_REPO: mongo
      MONGO_URI: mongodb://mongo:27017
      MONGO_DB_NAME: addresses_db
      MONGO_DB_COLLECTION: addresses

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
